In [1]:
import sqlite3
import pandas as pd

In [2]:
# Create your connection.
cnx = sqlite3.connect('bellybutton.sqlite')

In [4]:
cursor = cnx.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('samples',), ('sample_metadata',)]

In [6]:
df = pd.read_sql_query("SELECT * FROM samples", cnx)
df.head(20)

,otu_id,otu_label,940,941,943,944,945,946,947,948,...,1562,1563,1564,1572,1573,1574,1576,1577,1581,1601
0,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
5,6,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
6,7,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
7,8,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,1,0,0,0,0,0,0,0
8,9,Bacteria,0,0,0,0,0,1,0,0.0,...,0,0,0,0,0,0,0,0,0,0
9,10,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
10,11,Bacteria,1,0,0,0,0,0,0,1.0,...,0,0,0,0,0,0,0,0,0,0
11,12,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
12,13,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
13,14,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
14,15,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
15,16,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
16,17,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
17,18,Bacteria,0,0,0,0,0,2,1,0.0,...,0,0,0,0,0,0,0,0,0,0
18,19,Bacteria,1,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
19,20,Bacteria,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0